package core.views;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author natal
 */
public class ChoosePath extends javax.swing.JPanel {

    /**
     * Creates new form CloseEnough
     */
    public ChoosePath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        LeftArrow_btn = new javax.swing.JLabel();
        RightArrow_btn = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Where to?");
        Title.setInheritsPopupMenu(false);
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 50));

        LeftArrow_btn.setBackground(new java.awt.Color(153, 255, 153));
        LeftArrow_btn.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        LeftArrow_btn.setForeground(new java.awt.Color(51, 51, 51));
        LeftArrow_btn.setText("  < Left");
        LeftArrow_btn.setOpaque(true);
        add(LeftArrow_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 65));

        RightArrow_btn.setBackground(new java.awt.Color(153, 255, 153));
        RightArrow_btn.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        RightArrow_btn.setForeground(new java.awt.Color(51, 51, 51));
        RightArrow_btn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RightArrow_btn.setText("Right >   ");
        RightArrow_btn.setOpaque(true);
        add(RightArrow_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 180, 65));

        Map.setForeground(new java.awt.Color(204, 255, 204));
        Map.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map.setText("jLabel1");
        Map.setOpaque(true);
        add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 160));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LeftArrow_btn;
    private javax.swing.JLabel Map;
    private javax.swing.JLabel RightArrow_btn;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
