package core.views;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author natal
 */
public class CloseEnough extends javax.swing.JPanel {

    /**
     * Creates new form CloseEnough
     */
    public CloseEnough() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        ClueTitle = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();
        Again_btn = new javax.swing.JLabel();
        Clue_R = new javax.swing.JLabel();
        Clue_L = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClueTitle.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        ClueTitle.setForeground(new java.awt.Color(51, 51, 51));
        ClueTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClueTitle.setText("Not quite close enough!");
        add(ClueTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 400, 50));

        Map.setForeground(new java.awt.Color(204, 255, 204));
        Map.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map.setText("jLabel1");
        Map.setOpaque(true);
        add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 160));

        Again_btn.setBackground(new java.awt.Color(153, 255, 153));
        Again_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Again_btn.setForeground(new java.awt.Color(51, 51, 51));
        Again_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Again_btn.setText("Try again");
        Again_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Again_btn.setOpaque(true);
        add(Again_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));

        Clue_R.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Clue_R.setForeground(new java.awt.Color(0, 153, 153));
        Clue_R.setText("A lil to the right, you got it!");
        add(Clue_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 220, -1));

        Clue_L.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Clue_L.setForeground(new java.awt.Color(0, 153, 153));
        Clue_L.setText("A lil to the left, you got it!");
        add(Clue_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 220, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Again_btn;
    private javax.swing.JLabel ClueTitle;
    private javax.swing.JLabel Clue_L;
    private javax.swing.JLabel Clue_R;
    private javax.swing.JLabel Map;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    // End of variables declaration//GEN-END:variables
}
