package core.views;

import bstree.BSTree;
import bstree.Node;
import core.controllers.GameController;
import core.controllers.utils.Response;
import core.controllers.utils.Status;
import core.models.Game;
import core.models.Player;
import core.models.worlds.ComplexWorld;
import core.models.worlds.SimpleWorld;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author natal
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public Game game;
    public Player player;
    public static Node destiny;
    public Main() {
        this.player = new Player("player");
        this.game = new Game(this.player);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        MainTitle = new javax.swing.JLabel();
        NewGame_btn = new javax.swing.JLabel();
        Extit_btn = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        Title2 = new javax.swing.JLabel();
        Option1 = new javax.swing.JLabel();
        Option2 = new javax.swing.JLabel();
        Option3 = new javax.swing.JLabel();
        Exit_btn = new javax.swing.JLabel();
        pathPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        LeftArrow_btn = new javax.swing.JLabel();
        RightArrow_btn = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        endingPanel = new javax.swing.JPanel();
        WinTitle = new javax.swing.JLabel();
        Exit_btn1 = new javax.swing.JLabel();
        Again_btn = new javax.swing.JLabel();
        badEndingPanel = new javax.swing.JPanel();
        ClueTitle = new javax.swing.JLabel();
        Again_btn1 = new javax.swing.JLabel();
        Clue_R = new javax.swing.JLabel();
        Clue_L = new javax.swing.JLabel();
        textArea2 = new java.awt.TextArea();
        simplePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Question_Atxt = new javax.swing.JTextArea();
        InputBox_Ftxt = new javax.swing.JTextField();
        Submit_btn = new javax.swing.JLabel();
        textArea3 = new java.awt.TextArea();
        complexPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Question_Atxt1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Opt1_Atxt = new javax.swing.JTextArea();
        Check1 = new javax.swing.JCheckBox();
        Ans_Opt1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Opt2_Atxt = new javax.swing.JTextArea();
        Check2 = new javax.swing.JCheckBox();
        Ans_Opt2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Opt3_Atxt = new javax.swing.JTextArea();
        Check3 = new javax.swing.JCheckBox();
        Ans_Opt3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Opt4_Atxt = new javax.swing.JTextArea();
        Check5 = new javax.swing.JCheckBox();
        Ans_Opt4 = new javax.swing.JLabel();
        Submit_btn1 = new javax.swing.JLabel();
        textArea4 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 480));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        daPanel.setBackground(new java.awt.Color(255, 255, 255));
        daPanel.setMinimumSize(new java.awt.Dimension(770, 480));
        daPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setName(""); // NOI18N
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainTitle.setBackground(new java.awt.Color(204, 255, 204));
        MainTitle.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(51, 51, 51));
        MainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitle.setText("Welcome");
        menuPanel.add(MainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 370, 60));

        NewGame_btn.setBackground(new java.awt.Color(153, 255, 153));
        NewGame_btn.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        NewGame_btn.setForeground(new java.awt.Color(51, 51, 51));
        NewGame_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewGame_btn.setText("New Game");
        NewGame_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewGame_btn.setOpaque(true);
        NewGame_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NewGame_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NewGame_btnMouseReleased(evt);
            }
        });
        menuPanel.add(NewGame_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 160, 40));

        Extit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Extit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Extit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Extit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Extit_btn.setText("Leave");
        Extit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Extit_btn.setOpaque(true);
        Extit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Extit_btnMousePressed(evt);
            }
        });
        menuPanel.add(Extit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 160, 40));

        daPanel.add(menuPanel, "card2");

        optionPanel.setBackground(new java.awt.Color(255, 255, 255));
        optionPanel.setMinimumSize(new java.awt.Dimension(770, 480));
        optionPanel.setPreferredSize(new java.awt.Dimension(770, 480));
        optionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title2.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        Title2.setForeground(new java.awt.Color(51, 51, 51));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("Select your adventure");
        optionPanel.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 380, 50));

        Option1.setBackground(new java.awt.Color(51, 51, 51));
        Option1.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Option1.setForeground(new java.awt.Color(153, 255, 153));
        Option1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option1.setText("Option 1");
        Option1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option1.setOpaque(true);
        Option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Option1MousePressed(evt);
            }
        });
        optionPanel.add(Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 200, 50));

        Option2.setBackground(new java.awt.Color(51, 51, 51));
        Option2.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Option2.setForeground(new java.awt.Color(153, 255, 153));
        Option2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option2.setText("Option 2");
        Option2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option2.setOpaque(true);
        Option2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Option2MousePressed(evt);
            }
        });
        optionPanel.add(Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 50));

        Option3.setBackground(new java.awt.Color(51, 51, 51));
        Option3.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Option3.setForeground(new java.awt.Color(153, 255, 153));
        Option3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option3.setText("Option 3");
        Option3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option3.setOpaque(true);
        Option3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Option3MousePressed(evt);
            }
        });
        optionPanel.add(Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 200, 50));

        Exit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Exit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Exit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit_btn.setText("Back");
        Exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit_btn.setOpaque(true);
        Exit_btn.setPreferredSize(new java.awt.Dimension(38, 16));
        optionPanel.add(Exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, 40));

        daPanel.add(optionPanel, "card3");

        pathPanel.setBackground(new java.awt.Color(255, 255, 255));
        pathPanel.setMinimumSize(new java.awt.Dimension(770, 480));
        pathPanel.setPreferredSize(new java.awt.Dimension(770, 480));
        pathPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Where to?");
        Title.setInheritsPopupMenu(false);
        pathPanel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 50));

        LeftArrow_btn.setBackground(new java.awt.Color(153, 255, 153));
        LeftArrow_btn.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        LeftArrow_btn.setForeground(new java.awt.Color(51, 51, 51));
        LeftArrow_btn.setText("  < Left");
        LeftArrow_btn.setOpaque(true);
        LeftArrow_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LeftArrow_btnMousePressed(evt);
            }
        });
        pathPanel.add(LeftArrow_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 65));

        RightArrow_btn.setBackground(new java.awt.Color(153, 255, 153));
        RightArrow_btn.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        RightArrow_btn.setForeground(new java.awt.Color(51, 51, 51));
        RightArrow_btn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RightArrow_btn.setText("Right >   ");
        RightArrow_btn.setOpaque(true);
        RightArrow_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RightArrow_btnMousePressed(evt);
            }
        });
        pathPanel.add(RightArrow_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 180, 65));

        Map.setBackground(new java.awt.Color(51, 51, 51));
        Map.setForeground(new java.awt.Color(204, 255, 204));
        Map.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map.setText("jLabel1");
        Map.setOpaque(true);
        pathPanel.add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 160, 160));

        textArea1.setBackground(new java.awt.Color(51, 51, 51));
        textArea1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textArea1.setForeground(new java.awt.Color(204, 255, 204));
        pathPanel.add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 180, 180));

        daPanel.add(pathPanel, "card4");

        endingPanel.setBackground(new java.awt.Color(255, 255, 255));
        endingPanel.setMinimumSize(new java.awt.Dimension(770, 480));
        endingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WinTitle.setBackground(new java.awt.Color(0, 204, 51));
        WinTitle.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        WinTitle.setForeground(new java.awt.Color(0, 153, 51));
        WinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinTitle.setText("Congrats! You won!");
        endingPanel.add(WinTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 360, 50));

        Exit_btn1.setBackground(new java.awt.Color(153, 255, 153));
        Exit_btn1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Exit_btn1.setForeground(new java.awt.Color(51, 51, 51));
        Exit_btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit_btn1.setText("Leave");
        Exit_btn1.setOpaque(true);
        Exit_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit_btn1MousePressed(evt);
            }
        });
        endingPanel.add(Exit_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 160, 40));

        Again_btn.setBackground(new java.awt.Color(153, 255, 153));
        Again_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Again_btn.setForeground(new java.awt.Color(51, 51, 51));
        Again_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Again_btn.setText("Try again");
        Again_btn.setOpaque(true);
        Again_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Again_btnMousePressed(evt);
            }
        });
        endingPanel.add(Again_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));

        daPanel.add(endingPanel, "card5");

        badEndingPanel.setBackground(new java.awt.Color(255, 255, 255));
        badEndingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClueTitle.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        ClueTitle.setForeground(new java.awt.Color(51, 51, 51));
        ClueTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClueTitle.setText("Not quite close enough!");
        badEndingPanel.add(ClueTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 400, 50));

        Again_btn1.setBackground(new java.awt.Color(153, 255, 153));
        Again_btn1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Again_btn1.setForeground(new java.awt.Color(51, 51, 51));
        Again_btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Again_btn1.setText("Try again");
        Again_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Again_btn1.setOpaque(true);
        Again_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Again_btn1MousePressed(evt);
            }
        });
        badEndingPanel.add(Again_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));

        Clue_R.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Clue_R.setForeground(new java.awt.Color(0, 153, 153));
        Clue_R.setText("A lil to the right, you got it!");
        badEndingPanel.add(Clue_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 220, -1));

        Clue_L.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Clue_L.setForeground(new java.awt.Color(0, 153, 153));
        Clue_L.setText("A lil to the left, you got it!");
        badEndingPanel.add(Clue_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 220, -1));

        textArea2.setBackground(new java.awt.Color(51, 51, 51));
        textArea2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textArea2.setForeground(new java.awt.Color(204, 255, 204));
        badEndingPanel.add(textArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 180));

        daPanel.add(badEndingPanel, "card6");

        simplePanel.setBackground(new java.awt.Color(255, 255, 255));
        simplePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Question_Atxt.setBackground(new java.awt.Color(51, 51, 51));
        Question_Atxt.setColumns(20);
        Question_Atxt.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Question_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Question_Atxt.setRows(5);
        Question_Atxt.setText("Here goes a question");
        jScrollPane1.setViewportView(Question_Atxt);

        simplePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 50));

        InputBox_Ftxt.setBackground(new java.awt.Color(51, 51, 51));
        InputBox_Ftxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        InputBox_Ftxt.setForeground(new java.awt.Color(204, 255, 204));
        InputBox_Ftxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputBox_Ftxt.setText("Here goes the answer");
        simplePanel.add(InputBox_Ftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 520, 80));

        Submit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Submit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Submit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit_btn.setText("Submit");
        Submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit_btn.setOpaque(true);
        Submit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Submit_btnMousePressed(evt);
            }
        });
        simplePanel.add(Submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));

        textArea3.setBackground(new java.awt.Color(51, 51, 51));
        textArea3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textArea3.setForeground(new java.awt.Color(204, 255, 204));
        simplePanel.add(textArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 180));

        daPanel.add(simplePanel, "card7");

        complexPanel.setBackground(new java.awt.Color(255, 255, 255));
        complexPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setToolTipText("Here goes a question");
        jScrollPane2.setOpaque(false);

        Question_Atxt1.setBackground(new java.awt.Color(51, 51, 51));
        Question_Atxt1.setColumns(20);
        Question_Atxt1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Question_Atxt1.setForeground(new java.awt.Color(204, 255, 204));
        Question_Atxt1.setLineWrap(true);
        Question_Atxt1.setRows(5);
        Question_Atxt1.setText("Here is a question");
        Question_Atxt1.setToolTipText("");
        Question_Atxt1.setWrapStyleWord(true);
        Question_Atxt1.setCaretColor(new java.awt.Color(51, 51, 51));
        Question_Atxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Question_Atxt1.setOpaque(false);
        Question_Atxt1.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        Question_Atxt1.setSelectionColor(new java.awt.Color(153, 255, 204));
        jScrollPane2.setViewportView(Question_Atxt1);

        complexPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 50));

        Opt1_Atxt.setBackground(new java.awt.Color(51, 51, 51));
        Opt1_Atxt.setColumns(20);
        Opt1_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt1_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt1_Atxt.setRows(5);
        Opt1_Atxt.setText("cosa 1");
        jScrollPane3.setViewportView(Opt1_Atxt);

        complexPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 40));

        Check1.setBackground(new java.awt.Color(153, 255, 153));
        Check1.setForeground(new java.awt.Color(60, 63, 65));
        complexPanel.add(Check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 20, 40));

        Ans_Opt1.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt1.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt1.setOpaque(true);
        complexPanel.add(Ans_Opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 40));

        Opt2_Atxt.setBackground(new java.awt.Color(51, 51, 51));
        Opt2_Atxt.setColumns(20);
        Opt2_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt2_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt2_Atxt.setRows(5);
        jScrollPane4.setViewportView(Opt2_Atxt);

        complexPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 40));

        Check2.setBackground(new java.awt.Color(153, 255, 153));
        complexPanel.add(Check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 20, 40));

        Ans_Opt2.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt2.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt2.setOpaque(true);
        complexPanel.add(Ans_Opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 40));

        Opt3_Atxt.setBackground(new java.awt.Color(51, 51, 51));
        Opt3_Atxt.setColumns(20);
        Opt3_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt3_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt3_Atxt.setRows(5);
        jScrollPane5.setViewportView(Opt3_Atxt);

        complexPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 190, 40));

        Check3.setBackground(new java.awt.Color(153, 255, 153));
        complexPanel.add(Check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 20, 40));

        Ans_Opt3.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt3.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt3.setOpaque(true);
        complexPanel.add(Ans_Opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, 40));

        Opt4_Atxt.setBackground(new java.awt.Color(51, 51, 51));
        Opt4_Atxt.setColumns(20);
        Opt4_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt4_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt4_Atxt.setRows(5);
        jScrollPane6.setViewportView(Opt4_Atxt);

        complexPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 190, 40));

        Check5.setBackground(new java.awt.Color(153, 255, 153));
        Check5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check5ActionPerformed(evt);
            }
        });
        complexPanel.add(Check5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 20, 40));

        Ans_Opt4.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt4.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt4.setOpaque(true);
        complexPanel.add(Ans_Opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 230, 40));

        Submit_btn1.setBackground(new java.awt.Color(153, 255, 153));
        Submit_btn1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Submit_btn1.setForeground(new java.awt.Color(51, 51, 51));
        Submit_btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit_btn1.setText("Submit");
        Submit_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit_btn1.setOpaque(true);
        Submit_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Submit_btn1MousePressed(evt);
            }
        });
        complexPanel.add(Submit_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));

        textArea4.setBackground(new java.awt.Color(51, 51, 51));
        textArea4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textArea4.setForeground(new java.awt.Color(204, 255, 204));
        complexPanel.add(textArea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 180));

        daPanel.add(complexPanel, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(daPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(daPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGame_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewGame_btnMouseReleased
        
    }//GEN-LAST:event_NewGame_btnMouseReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void NewGame_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewGame_btnMousePressed
        // TODO add your handling code here:
        daPanel.removeAll();
        daPanel.add(optionPanel);
        daPanel.repaint();
        daPanel.revalidate();
    }//GEN-LAST:event_NewGame_btnMousePressed

    private void Option1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Option1MousePressed
        // TODO add your handling code here:
        Response response = GameController.createTree(this.game, 1);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            //JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            textArea1.setText(this.game.getTree().TreePrinter());
            textArea2.setText(this.game.getTree().TreePrinter());
            textArea3.setText(this.game.getTree().TreePrinter());
            textArea4.setText(this.game.getTree().TreePrinter());
            daPanel.removeAll();
            daPanel.add(pathPanel);
            daPanel.repaint();
            daPanel.revalidate(); 
            destiny = this.game.getTree().getRandomLeaf(this.game.getTree().root);
            System.out.println(destiny.data.getID());
        }
    }//GEN-LAST:event_Option1MousePressed

    private void Check5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check5ActionPerformed

    private void LeftArrow_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeftArrow_btnMousePressed
        // TODO add your handling code here:
        Response response = GameController.movePlayer(this.game, false);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            //JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            daPanel.removeAll();
            if(this.player.getLocation().data instanceof SimpleWorld) {
                daPanel.add(simplePanel);
                Question_Atxt.setText(this.player.getLocation().data.getQuestion());
            }else if (this.player.getLocation().data instanceof ComplexWorld) {
                daPanel.add(complexPanel);
                Question_Atxt1.setText(this.player.getLocation().data.getQuestion());
                ComplexWorld opt = (ComplexWorld) this.player.getLocation().data;
                Collections.shuffle(opt.getOptions());
                Opt1_Atxt.setText(opt.getOptions().get(0));
                Opt2_Atxt.setText(opt.getOptions().get(1));
                Opt3_Atxt.setText(opt.getOptions().get(2));
                Opt4_Atxt.setText(opt.getOptions().get(3));
            }
            daPanel.repaint();
            daPanel.revalidate();
        }
    }//GEN-LAST:event_LeftArrow_btnMousePressed

    private void RightArrow_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RightArrow_btnMousePressed
        // TODO add your handling code here:
        Response response = GameController.movePlayer(this.game, true);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            //JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            daPanel.removeAll();
            if(this.player.getLocation().data instanceof SimpleWorld) {
                daPanel.add(simplePanel);
                Question_Atxt.setText(this.player.getLocation().data.getQuestion());
            }else if (this.player.getLocation().data instanceof ComplexWorld) {
                daPanel.add(complexPanel);
                Question_Atxt1.setText(this.player.getLocation().data.getQuestion());
                ComplexWorld opt = (ComplexWorld) this.player.getLocation().data;
                Collections.shuffle(opt.getOptions());
                Opt1_Atxt.setText(opt.getOptions().get(0));
                Opt2_Atxt.setText(opt.getOptions().get(1));
                Opt3_Atxt.setText(opt.getOptions().get(2));
                Opt4_Atxt.setText(opt.getOptions().get(3));
            }
            daPanel.repaint();
            daPanel.revalidate();
        }
    }//GEN-LAST:event_RightArrow_btnMousePressed

    private void Submit_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit_btnMousePressed
        // TODO add your handling code here:
        Response response = GameController.makeUpdate(this.game, InputBox_Ftxt.getText());
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            daPanel.removeAll();
            if(!BSTree.hasChilds(this.player.getLocation())) {
                System.out.println(this.player.getLocation().data.getID());
               if(destiny.data.getID() == this.player.getLocation().data.getID()) {
                   daPanel.add(endingPanel);
               }else {
                   daPanel.add(badEndingPanel);
                   if(this.player.getLocation().data.getID() > destiny.data.getID()) {
                       Clue_L.setVisible(true);
                       Clue_R.setVisible(false);
                   }else {
                       Clue_L.setVisible(false);
                       Clue_R.setVisible(true);
                   }
               }
            }else {
                daPanel.add(pathPanel);
            }

            daPanel.repaint();
            daPanel.revalidate();
        }
        Question_Atxt.setText(this.player.getLocation().data.getQuestion());
        InputBox_Ftxt.setText("");
    }//GEN-LAST:event_Submit_btnMousePressed

    private void Submit_btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit_btn1MousePressed
        // TODO add your handling code here:
        boolean[] marked = new boolean[4];
        String[] answers = new String[4];
        
        marked[0] = Check1.isSelected();
        marked[1] = Check2.isSelected();
        marked[2] = Check3.isSelected();
        marked[3] = Check5.isSelected();
        
        answers[0] = Opt1_Atxt.getText();
        answers[1] = Opt2_Atxt.getText();
        answers[2] = Opt3_Atxt.getText();
        answers[3] = Opt4_Atxt.getText();
        
        Response response = GameController.makeUpdate(this.game, marked, answers);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            daPanel.removeAll();
            if(!BSTree.hasChilds(this.player.getLocation())) {
                System.out.println(this.player.getLocation().data.getID());
               if(destiny.data.getID() == this.player.getLocation().data.getID()) {
                   daPanel.add(endingPanel);
               }else {
                   daPanel.add(badEndingPanel);
                   if(this.player.getLocation().data.getID() > destiny.data.getID()) {
                       Clue_L.setVisible(true);
                       Clue_R.setVisible(false);
                   }else {
                       Clue_L.setVisible(false);
                       Clue_R.setVisible(true);
                   }
               }
            }else {
                daPanel.add(pathPanel);
            }

            daPanel.repaint();
            daPanel.revalidate();
        }
        Question_Atxt1.setText(this.player.getLocation().data.getQuestion());
        ComplexWorld opt = (ComplexWorld) this.player.getLocation().data;
        Collections.shuffle(opt.getOptions());
        Opt1_Atxt.setText(opt.getOptions().get(0));
        Opt2_Atxt.setText(opt.getOptions().get(1));
        Opt3_Atxt.setText(opt.getOptions().get(2));
        Opt4_Atxt.setText(opt.getOptions().get(3));
    }//GEN-LAST:event_Submit_btn1MousePressed

    private void Extit_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Extit_btnMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Extit_btnMousePressed

    private void Exit_btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_btn1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit_btn1MousePressed

    private void Again_btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Again_btn1MousePressed
        // TODO add your handling code here:
        Response response =  GameController.makeRestart(this.game);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            destiny = this.game.getTree().getRandomLeaf(this.game.getTree().root);
            daPanel.removeAll();
            daPanel.add(pathPanel);
            daPanel.repaint();
            daPanel.revalidate();
        }
    }//GEN-LAST:event_Again_btn1MousePressed

    private void Option2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Option2MousePressed
        // TODO add your handling code here:
        Response response = GameController.createTree(this.game, 2);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            //JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            textArea1.setText(this.game.getTree().TreePrinter());
            textArea2.setText(this.game.getTree().TreePrinter());
            textArea3.setText(this.game.getTree().TreePrinter());
            textArea4.setText(this.game.getTree().TreePrinter());
            daPanel.removeAll();
            daPanel.add(pathPanel);
            daPanel.repaint();
            daPanel.revalidate(); 
            destiny = this.game.getTree().getRandomLeaf(this.game.getTree().root);
            System.out.println(destiny.data.getID());
        }
    }//GEN-LAST:event_Option2MousePressed

    private void Option3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Option3MousePressed
        // TODO add your handling code here:
        Response response = GameController.createTree(this.game, 3);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            //JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            textArea1.setText(this.game.getTree().TreePrinter());
            textArea2.setText(this.game.getTree().TreePrinter());
            textArea3.setText(this.game.getTree().TreePrinter());
            textArea4.setText(this.game.getTree().TreePrinter());
            daPanel.removeAll();
            daPanel.add(pathPanel);
            daPanel.repaint();
            daPanel.revalidate(); 
            destiny = this.game.getTree().getRandomLeaf(this.game.getTree().root);
            System.out.println(destiny.data.getID());
        }
        
    }//GEN-LAST:event_Option3MousePressed

    private void Again_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Again_btnMousePressed
        // TODO add your handling code here:
        Response response =  GameController.makeRestart(this.game);
        
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            destiny = this.game.getTree().getRandomLeaf(this.game.getTree().root);
            daPanel.removeAll();
            daPanel.add(pathPanel);
            daPanel.repaint();
            daPanel.revalidate();
        }
    }//GEN-LAST:event_Again_btnMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Again_btn;
    private javax.swing.JLabel Again_btn1;
    private javax.swing.JLabel Ans_Opt1;
    private javax.swing.JLabel Ans_Opt2;
    private javax.swing.JLabel Ans_Opt3;
    private javax.swing.JLabel Ans_Opt4;
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JCheckBox Check5;
    private javax.swing.JLabel ClueTitle;
    private javax.swing.JLabel Clue_L;
    private javax.swing.JLabel Clue_R;
    private javax.swing.JLabel Exit_btn;
    private javax.swing.JLabel Exit_btn1;
    private javax.swing.JLabel Extit_btn;
    private javax.swing.JTextField InputBox_Ftxt;
    private javax.swing.JLabel LeftArrow_btn;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel Map;
    private javax.swing.JLabel NewGame_btn;
    private javax.swing.JTextArea Opt1_Atxt;
    private javax.swing.JTextArea Opt2_Atxt;
    private javax.swing.JTextArea Opt3_Atxt;
    private javax.swing.JTextArea Opt4_Atxt;
    private javax.swing.JLabel Option1;
    private javax.swing.JLabel Option2;
    private javax.swing.JLabel Option3;
    private javax.swing.JTextArea Question_Atxt;
    private javax.swing.JTextArea Question_Atxt1;
    private javax.swing.JLabel RightArrow_btn;
    private javax.swing.JLabel Submit_btn;
    private javax.swing.JLabel Submit_btn1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel WinTitle;
    private javax.swing.JPanel badEndingPanel;
    private javax.swing.JPanel complexPanel;
    private javax.swing.JPanel daPanel;
    private javax.swing.JPanel endingPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel pathPanel;
    private javax.swing.JPanel simplePanel;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    private java.awt.TextArea textArea3;
    private java.awt.TextArea textArea4;
    // End of variables declaration//GEN-END:variables
}
