package core.views;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author natal
 */
public class Question_Input extends javax.swing.JPanel {

    /**
     * Creates new form CloseEnough
     */
    public Question_Input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Question_Atxt = new javax.swing.JTextArea();
        InputBox_Ftxt = new javax.swing.JTextField();
        Map = new javax.swing.JLabel();
        Submit_btn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Question_Atxt.setColumns(20);
        Question_Atxt.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Question_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Question_Atxt.setRows(5);
        Question_Atxt.setText("Here goes a question");
        jScrollPane1.setViewportView(Question_Atxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 50));

        InputBox_Ftxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        InputBox_Ftxt.setForeground(new java.awt.Color(204, 255, 204));
        InputBox_Ftxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputBox_Ftxt.setText("Here goes the answer");
        add(InputBox_Ftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 520, 80));

        Map.setForeground(new java.awt.Color(204, 255, 204));
        Map.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map.setText("jLabel1");
        Map.setOpaque(true);
        add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 160));

        Submit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Submit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Submit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit_btn.setText("Submit");
        Submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit_btn.setOpaque(true);
        add(Submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputBox_Ftxt;
    private javax.swing.JLabel Map;
    private javax.swing.JTextArea Question_Atxt;
    private javax.swing.JLabel Submit_btn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
