package core.views;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author natal
 */
public class Question_Multiple extends javax.swing.JPanel {

    /**
     * Creates new form CloseEnough
     */
    public Question_Multiple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Question_Atxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Opt1_Atxt = new javax.swing.JTextArea();
        Check1 = new javax.swing.JCheckBox();
        Ans_Opt1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Opt2_Atxt = new javax.swing.JTextArea();
        Check2 = new javax.swing.JCheckBox();
        Ans_Opt2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Opt3_Atxt = new javax.swing.JTextArea();
        Check3 = new javax.swing.JCheckBox();
        Ans_Opt3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Opt4_Atxt = new javax.swing.JTextArea();
        Check4 = new javax.swing.JCheckBox();
        Ans_Opt4 = new javax.swing.JLabel();
        Submit_btn = new javax.swing.JLabel();
        Map = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setToolTipText("Here goes a question");
        jScrollPane1.setOpaque(false);

        Question_Atxt.setColumns(20);
        Question_Atxt.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Question_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Question_Atxt.setLineWrap(true);
        Question_Atxt.setRows(5);
        Question_Atxt.setText("Here is a question");
        Question_Atxt.setToolTipText("");
        Question_Atxt.setWrapStyleWord(true);
        Question_Atxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Question_Atxt.setOpaque(false);
        Question_Atxt.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        Question_Atxt.setSelectionColor(new java.awt.Color(153, 255, 204));
        jScrollPane1.setViewportView(Question_Atxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 370, 50));

        Opt1_Atxt.setColumns(20);
        Opt1_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt1_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt1_Atxt.setRows(5);
        Opt1_Atxt.setText("cosa 1");
        jScrollPane2.setViewportView(Opt1_Atxt);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 40));
        add(Check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 120, 40));

        Ans_Opt1.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt1.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt1.setOpaque(true);
        add(Ans_Opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 40));

        Opt2_Atxt.setColumns(20);
        Opt2_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt2_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt2_Atxt.setRows(5);
        jScrollPane3.setViewportView(Opt2_Atxt);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 40));
        add(Check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, 40));

        Ans_Opt2.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt2.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt2.setOpaque(true);
        add(Ans_Opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 40));

        Opt3_Atxt.setColumns(20);
        Opt3_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt3_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt3_Atxt.setRows(5);
        jScrollPane4.setViewportView(Opt3_Atxt);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 190, 40));
        add(Check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 120, 40));

        Ans_Opt3.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt3.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt3.setOpaque(true);
        add(Ans_Opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, 40));

        Opt4_Atxt.setColumns(20);
        Opt4_Atxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Opt4_Atxt.setForeground(new java.awt.Color(204, 255, 204));
        Opt4_Atxt.setRows(5);
        jScrollPane5.setViewportView(Opt4_Atxt);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 190, 40));

        Check4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check4ActionPerformed(evt);
            }
        });
        add(Check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 120, 40));

        Ans_Opt4.setBackground(new java.awt.Color(153, 255, 153));
        Ans_Opt4.setForeground(new java.awt.Color(51, 51, 51));
        Ans_Opt4.setOpaque(true);
        add(Ans_Opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 230, 40));

        Submit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Submit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Submit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit_btn.setText("Submit");
        Submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit_btn.setOpaque(true);
        add(Submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));

        Map.setForeground(new java.awt.Color(204, 255, 204));
        Map.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Map.setText("jLabel1");
        Map.setOpaque(true);
        add(Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void Check4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ans_Opt1;
    private javax.swing.JLabel Ans_Opt2;
    private javax.swing.JLabel Ans_Opt3;
    private javax.swing.JLabel Ans_Opt4;
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JCheckBox Check4;
    private javax.swing.JLabel Map;
    private javax.swing.JTextArea Opt1_Atxt;
    private javax.swing.JTextArea Opt2_Atxt;
    private javax.swing.JTextArea Opt3_Atxt;
    private javax.swing.JTextArea Opt4_Atxt;
    private javax.swing.JTextArea Question_Atxt;
    private javax.swing.JLabel Submit_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
