package core.views;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author natal
 */
public class Select extends javax.swing.JPanel {

    /**
     * Creates new form Select
     */
    public Select() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title2 = new javax.swing.JLabel();
        Option1 = new javax.swing.JLabel();
        Option2 = new javax.swing.JLabel();
        Option3 = new javax.swing.JLabel();
        Exit_btn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title2.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        Title2.setForeground(new java.awt.Color(51, 51, 51));
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("Select your adventure");
        add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 380, 50));

        Option1.setBackground(new java.awt.Color(51, 51, 51));
        Option1.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Option1.setForeground(new java.awt.Color(153, 255, 153));
        Option1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option1.setText("Option 1");
        Option1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option1.setOpaque(true);
        add(Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 200, 50));

        Option2.setBackground(new java.awt.Color(51, 51, 51));
        Option2.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Option2.setForeground(new java.awt.Color(153, 255, 153));
        Option2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option2.setText("Option 2");
        Option2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option2.setOpaque(true);
        add(Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 50));

        Option3.setBackground(new java.awt.Color(51, 51, 51));
        Option3.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Option3.setForeground(new java.awt.Color(153, 255, 153));
        Option3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Option3.setText("Option 3");
        Option3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Option3.setOpaque(true);
        add(Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 200, 50));

        Exit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Exit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Exit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit_btn.setText("Back");
        Exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit_btn.setOpaque(true);
        Exit_btn.setPreferredSize(new java.awt.Dimension(38, 16));
        add(Exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit_btn;
    private javax.swing.JLabel Option1;
    private javax.swing.JLabel Option2;
    private javax.swing.JLabel Option3;
    private javax.swing.JLabel Title2;
    // End of variables declaration//GEN-END:variables
}
