package core.views;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author natal
 */
public class Win_End extends javax.swing.JPanel {

    /**
     * Creates new form Win_End
     */
    public Win_End() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WinTitle = new javax.swing.JLabel();
        Exit_btn = new javax.swing.JLabel();
        Again_btn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WinTitle.setBackground(new java.awt.Color(0, 204, 51));
        WinTitle.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        WinTitle.setForeground(new java.awt.Color(0, 153, 51));
        WinTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinTitle.setText("Congrats! You won!");
        add(WinTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 360, 50));

        Exit_btn.setBackground(new java.awt.Color(153, 255, 153));
        Exit_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Exit_btn.setForeground(new java.awt.Color(51, 51, 51));
        Exit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit_btn.setText("Leave");
        Exit_btn.setOpaque(true);
        add(Exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, 40));

        Again_btn.setBackground(new java.awt.Color(153, 255, 153));
        Again_btn.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Again_btn.setForeground(new java.awt.Color(51, 51, 51));
        Again_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Again_btn.setText("Try again");
        Again_btn.setOpaque(true);
        add(Again_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 160, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Again_btn;
    private javax.swing.JLabel Exit_btn;
    private javax.swing.JLabel WinTitle;
    // End of variables declaration//GEN-END:variables
}
